### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by asbjornenge**
Have a look 😄 

//cc @mrfelton

### CODE REVIEW

**Comment by asbjornenge** [comment]
@mrfelton There we are 😄 Take a look! It had a HUGE impact on image size 😛 Went from `1.38 GB` to `65 MB` 🎉😂 I don't work with GO a lot and forget that it's all binaries 😉

**Comment by asbjornenge** [comment]
//cc @mrfelton did you forget? 😛 🔔 🙈

**Comment by mrfelton** [comment]
Hey @asbjornenge - Will try to get onto this soon. Thanks for the reminder :)

**Comment by mrfelton** [comment]
Hi @asbjornenge . I spent a but of time on this today. I actually didn't use this PR directly in the end as I wanted to try to keep `docker-lnd` inline with `docker-btcd`, but really - thank you a lot for your contribution. We now have the following:

LND
- https://github.com/LN-Zap/docker-lnd
- https://hub.docker.com/r/lnzap/lnd

BTCD
- https://github.com/LN-Zap/docker-btcd
- https://hub.docker.com/r/lnzap/btcd

**Pull request closed without merging**
